apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels:
    app: frontend-app
    type: frontend
spec:
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-app
        type: frontend
    spec:
      containers:
        - name: frontend-container
          image: nginx:1.19.4
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      type: frontend
  strategy:
    type: RollingUpdate # ou Recreate
  replicas: 6